import json
import time
import requests
import subprocess

SIEM_URL = "http://localhost:8000/api/v1/ingest"

def process_waf_log(log_line):
    try:
        data = json.loads(log_line)
        
        if "transaction" in data:
            t = data["transaction"]
            client_ip = t.get("client_ip", "Unknown")
            uri = t.get("request", {}).get("uri", "")
            
            # Messages (rule violations) generated by the WAF
            messages = t.get("messages", [])
            for msg_data in messages:
                rule_id = msg_data.get("details", {}).get("ruleId", "N/A")
                alert_msg = msg_data.get("message", "Unknown Alert")
                
                # "Host header is IP"
                if rule_id == "920350":
                    continue 

                
                raw_message = f"[WAF RULE {rule_id}] {alert_msg} | Payload: {uri}"
                
                payload = {
                    "source_ip": client_ip,
                    "device_id": "owasp-waf-node1",
                    "event_type": "web_request",
                    "raw_message": raw_message,
                    "message": raw_message
                }
                
                # SIEM Backend
                response = requests.post(SIEM_URL, json=payload)
                print(f"🚨 [WAF -> SIEM] Transmitted: {raw_message} (Status: {response.status_code})")
                
                break # Single log for the same attack
                
    except json.JSONDecodeError:
        pass # Don't care if this line is not JSON (if it is an Nginx initialization log)

def start_agent():
    print("🛡️ WAF Agent Has Started! ModSecurity logs are resting in the air...")
    
    # It can be read live by running the command "docker logs --follow siem-waf" from within Python
    process = subprocess.Popen(
        ["docker", "logs", "--follow", "siem-waf"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True
    )
    
    # Log in infinite loop
    for line in process.stdout:
        if '{"transaction":' in line:
            process_waf_log(line.strip())

if __name__ == "__main__":
    start_agent()